name: Lint

on:
  push:
    branches:
      - '*'

jobs:
  analyze:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 16.0.0, 16 ]
      fail-fast: false

    steps:
      - name: Checkout project
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache Node dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Run code standards checks
        run: npm run code-standards
